project:
  type: website
  output-dir: docs

website:
  title: "Documentation of Roy's Scripts"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "API Reference"
        href: sphinx-api-website/index.html

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



